### ISSUE TITLE
При нек-й коллизии TypeError: '<=' not supported between instances of 'float' and 'NoneType'

### ISSUE THREAD

**Issue by UltraMadd** [UltraMadd/stu_project_game#4]
```
Traceback (most recent call last):
  File "/media/wks/code/py/stu_project_game/src/main.py", line 139, in <module>
    main()
  File "/media/wks/code/py/stu_project_game/src/main.py", line 135, in main
    game.run()
  File "/media/wks/code/py/stu_project_game/src/main.py", line 128, in run
    arcade.run()
  File "/media/wks/code/py/stu_project_game/venv/lib/python3.11/site-packages/arcade/window_commands.py", line 289, in run
    pyglet.app.run()
  File "/media/wks/code/py/stu_project_game/venv/lib/python3.11/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run(interval)
  File "/media/wks/code/py/stu_project_game/venv/lib/python3.11/site-packages/pyglet/app/base.py", line 184, in run
    timeout = self.idle()
              ^^^^^^^^^^^
  File "/media/wks/code/py/stu_project_game/venv/lib/python3.11/site-packages/pyglet/app/base.py", line 245, in idle
    self.clock.call_scheduled_functions(dt)
  File "/media/wks/code/py/stu_project_game/venv/lib/python3.11/site-packages/pyglet/clock.py", line 277, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/media/wks/code/py/stu_project_game/venv/lib/python3.11/site-packages/arcade/application.py", line 318, in _dispatch_updates
    self.dispatch_event('on_update', delta_time)
  File "/media/wks/code/py/stu_project_game/venv/lib/python3.11/site-packages/pyglet/window/__init__.py", line 1361, in dispatch_event
    super().dispatch_event(*args)
  File "/media/wks/code/py/stu_project_game/venv/lib/python3.11/site-packages/pyglet/event.py", line 418, in dispatch_event
    self._raise_dispatch_exception(event_type, args, handler, exception)
  File "/media/wks/code/py/stu_project_game/venv/lib/python3.11/site-packages/pyglet/event.py", line 481, in _raise_dispatch_exception
    raise exception
  File "/media/wks/code/py/stu_project_game/venv/lib/python3.11/site-packages/pyglet/event.py", line 415, in dispatch_event
    if handler(*args):
       ^^^^^^^^^^^^^^
  File "/media/wks/code/py/stu_project_game/src/main.py", line 64, in on_update
    self.physics_engine.update()
  File "/media/wks/code/py/stu_project_game/venv/lib/python3.11/site-packages/arcade/physics_engines.py", line 245, in update
    return _move_sprite(self.player_sprite, self.walls, ramp_up=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/wks/code/py/stu_project_game/venv/lib/python3.11/site-packages/arcade/physics_engines.py", line 82, in _move_sprite
    hit_list_x = check_for_collision_with_lists(moving_sprite, walls)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/wks/code/py/stu_project_game/venv/lib/python3.11/site-packages/arcade/sprite_list/spatial_hash.py", line 388, in check_for_collision_with_lists
    if sprite is not sprite2 and _check_for_collision(sprite, sprite2):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/wks/code/py/stu_project_game/venv/lib/python3.11/site-packages/arcade/sprite_list/spatial_hash.py", line 254, in _check_for_collision
    return are_polygons_intersecting(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/wks/code/py/stu_project_game/venv/lib/python3.11/site-packages/arcade/geometry_python.py", line 53, in are_polygons_intersecting
    if cast(float, max_a) <= cast(float, min_b) or cast(float, max_b) <= cast(float, min_a):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'float' and 'NoneType'
```

**Как воспроизвести**
Подойти к дереву (например идти вверх-влево к первому дереву) и столкнуться с ним (Не во всех точках, но в некоторых да).
![screenshot-20240419-135036Z-selected](https://github.com/UltraMadd/stu_project_game/assets/102500290/07110607-8b57-4c02-821f-f2fb72f01a4f)

**Comment by UltraMadd** [comment]
Вот оно - stu_project_game/map/Tiny Swords (Update 010)/Resources/Trees/Tree.png-320-0-64-64-False-False-False-Simple! из-за этого спрайта возникает пустой список в are_polygons_intersecting и min_b остается None. 
Получено с помощью
```python
print(sprite2.textures[0].name)
``` в check_for_collision_with_lists

**Comment by Mioxive** [comment]
> Вот оно - stu_project_game/map/Tiny Swords (Update 010)/Resources/Trees/Tree.png-320-0-64-64-False-False-False-Simple! из-за этого спрайта возникает пустой список в are_polygons_intersecting и min_b остается None. Получено с помощью
> 
> ```python
> print(sprite2.textures[0].name)
> ```
> 
> в check_for_collision_with_lists
> 
> у этого спрайта `hit_box_points = []`

я тогда найду новый спрайт дерева и заменю

**Comment by Mioxive** [comment]
```
  RequiredDependencyException:
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  <string>:45: RuntimeWarning: Pillow 9.3.0 does not support Python 3.12 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pillow
ERROR: Could not build wheels for pillow, which is required to install pyproject.toml-based projects
 

```

но я после обновления pycharm'а даже arcade установить не могу, раньше это фиксилось установлением build tools, но щас не помогает

**Comment by Mioxive** [comment]
![image](https://github.com/UltraMadd/stu_project_game/assets/96176845/178e60d2-0f4f-4859-a1f3-24ed71239501)
вот это дерево норм будет?

**Comment by UltraMadd** [comment]
Проблема скорей не в ассетах (да и так втзуально не понятно), а в том, как они лоадятся. Нужно понять почему есть много деревьев где он не пуст (список хитбокса) и почему появляется такое

**Comment by UltraMadd** [comment]
> ```
>   RequiredDependencyException:
>   
>   The headers or library files could not be found for zlib,
>   a required dependency when compiling Pillow from source.
>   
>   Please see the install instructions at:
>      https://pillow.readthedocs.io/en/latest/installation.html
>   
>   
>   <string>:45: RuntimeWarning: Pillow 9.3.0 does not support Python 3.12 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
>   [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for pillow
> ERROR: Could not build wheels for pillow, which is required to install pyproject.toml-based projects
>  
> 
> ```
> 
> но я после обновления pycharm'а даже arcade установить не могу, раньше это фиксилось установлением build tools, но щас не помогает

а зачем использовать 3.12? он же там вроде недавно релизнулся?.. или я ошибаюсь

**Comment by Mioxive** [comment]
> > ```
> >   RequiredDependencyException:
> >   
> >   The headers or library files could not be found for zlib,
> >   a required dependency when compiling Pillow from source.
> >   
> >   Please see the install instructions at:
> >      https://pillow.readthedocs.io/en/latest/installation.html
> >   
> >   
> >   <string>:45: RuntimeWarning: Pillow 9.3.0 does not support Python 3.12 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
> >   [end of output]
> >   
> >   note: This error originates from a subprocess, and is likely not a problem with pip.
> >   ERROR: Failed building wheel for pillow
> > ERROR: Could not build wheels for pillow, which is required to install pyproject.toml-based projects
> >  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > но я после обновления pycharm'а даже arcade установить не могу, раньше это фиксилось установлением build tools, но щас не помогает
> 
> а зачем использовать 3.12? он же там вроде недавно релизнулся?.. или я ошибаюсь

а я и 3.11 ставил

**Comment by UltraMadd** [comment]
есть другой ишью, который по идее должен пофиксить это, не могу сделать сам сейчас, но это быстро

**Comment by Mioxive** [comment]
`sprite.hit_box_points = [(x1, y1), (x2, y2), (x3, y3), (x4, y4)]`
может попробовать задавать хитбокс вручную?

**Comment by UltraMadd** [comment]
Гыа! Крутой костыль! А как ты найдешь то, чему нужно задать этот хитбокс? методом тыка? а как определишь размер хитбокса? хотя у нас нет времени особо...

**Comment by Mioxive** [comment]
> Гыа! Крутой костыль! А как ты найдешь то, чему нужно задать этот хитбокс? методом тыка? а как определишь размер хитбокса? хотя у нас нет времени особо искать красивый метод...

я вообще хз что с этим делать

**Comment by Mioxive** [comment]
а как тогда

**Comment by Mioxive** [comment]
у меня у каждого дерева крашит, есчли сбоку подойти

**Comment by UltraMadd** [comment]
Лес вырубить и Китаю продать!
ну если получится твое решение, я за него.

**Comment by Mioxive** [comment]
я не знаю как реализовывать это

**Comment by Mioxive** [comment]
так, что то я не понимаю. я хотел анимацию персонажу добавить, мне это куда писать? в main.py или в game_view.py

**Comment by UltraMadd** [comment]
> так, что то я не понимаю. я хотел анимацию персонажу добавить, мне это куда писать? в main.py или в game_view.py

в мейн, game_view не используется, когда мержили так получилось.

**Comment by Mioxive** [comment]
скоро пофикшу, сам виноват, коллизию тайлам не сделал
